#!/bin/sh

export PATH=$PATH:/home/aem/bin

# Source scripts in /etc/X11/xinit/xinitrc.d/
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#    for f in /etc/X11/xinit/xinitrc.d/*; do
#        [ -x "$f" ] && . "$f"
#    done
#    unset f
#fi

# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GPG_AGENT_INFO SSH_AUTH_SOCK
unset SSH_ASKPASS

# Disable Caps lock
setxkbmap -option ctrl:nocaps
# Disable bell
xset -b
# Merge/Read .Xresources
xrdb ~/.Xresources
#Network Manager applet
nm-applet &
# Change delay rate
xset r rate 300 40
# Monitor off after 1hr
xset dpms 3600 3600 3600
# Lock screen after 5 minutes

# xautolock -time 5 -locker 'i3lock -c 000000' &
