#!/bin/sh

export PATH=$PATH:/home/aem/bin

# Source scripts in /etc/X11/xinit/xinitrc.d/
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#    for f in /etc/X11/xinit/xinitrc.d/*; do
#        [ -x "$f" ] && . "$f"
#    done
#    unset f
#fi

# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GPG_AGENT_INFO SSH_AUTH_SOCK
unset SSH_ASKPASS

#setxkbmap -option caps:none
# setxkbmap -option ctrl:nocaps
# xset -b
xrdb ~/.Xresources

#Network Manager applet
nm-applet &
