#!/bin/sh

export PATH=$PATH:/home/aem/bin

# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
# Disable Caps lock
setxkbmap -option ctrl:nocaps
# Disable bell
xset -b
# Disable touchpad
synclient TouchpadOff=1
# Merge/Read .Xresources
xrdb ~/.Xresources
# Mount helper
udiskie --tray &
#Network Manager applet
nm-applet &
# Change delay rate
xset r rate 300 40
# Monitor off after 1hr
xset dpms 3600 3600 3600
xset s off -dpms
nitrogen --restore
clipit &
# Lock screen after 5 minutes
# xautolock -time 5 -locker 'i3lock -c 000000' &
